spring.datasource.url=jdbc:sqlserver://demodbserver12.database.windows.net:1433;database=demodb;user=sqladmin@demodbserver12;password=Mindtree@4321;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}
