apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_DATASOURCE_URL: jdbc:sqlserver://dssqlserver101.database.windows.net:1433;database=gtedb;encrypt=true;trustServerCertificate=false;loginTimeout=30;
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
