apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.secret.dbUsername | b64enc }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc }}
